### PR TITLE
test13

### PR DESCRIPTION
**Pull request by b2z**
13

### CODE REVIEW

**Comment by b2z** [comment]
rrw

**Comment by b2z** [comment]
woot<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
back<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :red_circle: unsuccessfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :red_circle: unsuccessfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :red_circle: unsuccessfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<br /><br />Test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<br /><br />qeqeqeeqq<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<br /><br />Test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :red_circle: unsuccessfully on 37406171bf62d9f9f698f517917058026a6e76d3<br /><br />gdg<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by elkuku** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<br /><br />well well... :wink: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :red_circle: unsuccessfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :red_circle: unsuccessfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :red_circle: unsuccessfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :white_check_mark: successfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :red_circle: unsuccessfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Comment by b2z** [comment]
I have tested this item :red_circle: unsuccessfully on 37406171bf62d9f9f698f517917058026a6e76d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/16">jissues.j4devs.ru/jissues-test/16</a>.</sub>

**Pull request closed without merging**
