### PR TITLE
test language

### PR DESCRIPTION
**Pull request by zero-24**
.

### CODE REVIEW

**Comment by b2z** [comment]
Pull requests to the master branch of this repo are not accepted.  Please close this pull request and submit a new one against the staging branch.<br />_This is an automated message from the <a href="https://github.com/joomla/jissues">J!Tracker Application</a>._

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/22">jissues.j4devs.ru/jissues-test/22</a>.</sub>

**Comment by zero-24** [comment]
pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://jissues.j4devs.ru/tracker/jissues-test/22">jissues.j4devs.ru/jissues-test/22</a>.</sub>

**Comment by zero-24** [comment]
test

**Pull request closed without merging**
